#!/usr/bin/php -q
<?php
require __DIR__.'/vendor/autoload.php';

use App\Application;
use Cake\Console\CommandRunner;

$argv[1] = 'version';

\Cake\Log\Log::debug('Scheduler started ' . time());

// Build the runner with an application and root executable name.
$runner = new CommandRunner(new Application(__DIR__ . '/config'), 'cake');
exit($runner->run($argv));
